name: gov_booking_app
description: Government Booking System app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Networking + State
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1

  # Storage (Web + Windows)
  shared_preferences: ^2.2.3

  # UI
  google_fonts: ^6.3.0
  go_router: ^14.8.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
